###########################################################
# $File: demofail.py $
# $Author: daf $
# $Date: 2018-01-20 00:41:32 -0800 (Sat, 20 Jan 2018) $
# $Revision: 194 $
###########################################################

# Potential Bin Labels for Demo mode

demofail = [
    'Vcc Too High',
    'Vdd Too Low',
    'Fails Smoke Test',
    'Ohm a Phobic',
    'DUT Imploded',
    'Pellicle Dust',
    'Boron Subjects',
    'Fake Implants',
    'Reticle Occlusion',
    'Lattice InterLeaves',
    'Electron Rigidity',
    'Electron Cavitation',
    'Self-Test Expired',
    'Bilateral UJTs',
    'Open Drain Closure',
    'Mho Problems',
    'Lost Carry Bits',
    'Hexed Decimals',
    'Cache Registers',
    'Collector Dump',
    'Inductive Capacitance',
    'Probable Uncertainties',
    'Aggravated Passivation',
    'Conductance Reluctance',
    'Combative Resistance',
    'Passive Resistance',
    'Bohr-ing Electrons',
    "AND OR'ing",
    'Nano Particulation',
    'Electrons Scramming',
    'Worked on Paper',
    'Wye Knots',
    'Elevated Potential',
    'Wide Open Shorts',
    'ASCII Corruption',
    'SCR Scramming',
    'Burst Mode Fallout',
    'BiPolar Warming',
    'Cohabitating RAM',
    'Refresh Timeout',
    'Descriminator Fired',
    'Strobe Locking',
    'Low Potential',
    'Drain Clogging',
    'Tunneling Collapse',
    'Unsyncable Sinkers',
    'CMOS Bickering',
    'Relay Gossiping',
    'Gate Flatulence',
    'Loopy Antennae',
    'Roving Lattice',
    'Bad Timing',
    'Electron Stagnation',
    'Loose Volts',
    'MUX Fluxing',
    'Active Static',
    'Watts Up',
    'Diffusion Refusion',
    'Diametric Collusion',
    'Locked Gates',
    'Proton Sparking',
    'Sign Waves',
    'Mono-Poly',
    'Photon Escape',
    'E=IR Failure',
    'Unlucky',
    'DVT Ruts',
    'Electron Spin Rate',
    'Repelled Charges',
    'Resists Change',
    'Proton Charging',
    'Neutron Collision',
    'Wet Tank Circuits',
    'Quad Tri-States',
    'Electron Imbalance',
    'Long Shorts',
    'Gluon Polarization',
    'BIST Knotting',
    'Roving Ground',
    'Neutron Charging',
    'Quark Imbalance',
    'Gate Flutter',
    'Electron Rebelling',
    'Thermal Contraction',
    'Passive Reactance',
    'Phosphorus Glow',
    'Gettering Scatter',
    'Rapid Heat Loss',
    'Rapid Heat Gain',
    'Blown Two BITS',
    'Convection Limit',
    'Clamp Failure',
    'Floating Shorts',
    'Frigid Oscillator',
    'Diffusion Rust',
    'Bandgap Noise',
    'Avalanche CoverUp',
    'Flash Overload',
    'Electron Sputtering',
    'Rotating Lattice',
    'Electron Confusion',
    'Transverse Breakdown',
    'Creepy AlCu',
    'Toll Bridging',
    'Saturation Leakage',
    'Inhibition Loss',
    'Daraf Elastance',
    'Shot Keys',
    'Analog Digitation',
    'SCSI Bus Stop',
    'Harmonic Contortion',
    'Watchdog Barking',
    'Non Sense Resistor',
    'NANDed ANDing',
    'SMPS Seizure',
    'Pullup Letdown',
    'Shifty Registers',
    'CRC Vacillation',
    'Strobe Failure',
    'Cathode Dilation',
    'Digital Analogs',
    'Gain Loss',
    'Frequency Inhibition',
    'Wandering Step Coverage',
    "Quantum Propagation",
    'Crowbar Crosstalk',
    'Stressed Relaxations',
    'Coulomb Counter Full',
    'RFID Collision',
    'Develop Drips',
    'Burn-In Burnout',
    'UnPredictable',
    'Ripple Rejection',
    'BIT Robbing',
    'RTS Ignoring',
    'Thermal NonProtection',
    'Autoclave Avoidance',
    'Tempermental Thermistors',
    'Fault Intolerance',
    'Memory Loss',
    'Marketing Failure',
    'Cranky Diodes',
    'Doping Reject',
    'Harmonic Clipping',
    'Incoherent Sampling',
    'Fermi Paradox',
    'Faraday Fluctuations',
    'Escape Hatch Blown',
    'Cosmic Ray Bans',
    'Plasma Reticulation',
    'Endpoint Regeneration',
    'Mono Duplexing',
    'Quantum Flux',
    'Hollow Grounds',
    'Finite Loop Failure',
    'Test Anomalies',
    'Flux Capacitance',
    'Roaming Holes',
    'Sticky Polyimide',
    'Magnetic Gain Loss',
    'Galvanic Isolation',
    'GPIB Squawking',
    'Fail-Safe Failure',  
    ]