#---------------------------------------------------------------------

# This file was generated by Image2pyfile.py

from wx.lib.embeddedimage import PyEmbeddedImage

catalog = {}
#---------------------------------------------------------------------

refresh_png = PyEmbeddedImage( 
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAmtJ"
    "REFUOI2Nk01IVHEUxc/9z3vz1UzvDaMzuoh5jKWTFk60yAqalw3hok2LWduihIjIaFFCgbVr"
    "YxItoja1dqFQ0CIXL8hFFDSCDpaoL1QaDcd5avP1Pv4tJDIz9K4u3Ht+nAP3ErbV0cxANxdY"
    "fygsKaGwBIsD+YVlmKVKltt278TQrXdb9+l3czxzWypbvhEipnZeOINEezM2pHqM5S1MLplY"
    "+fwFka/vIdRWB3MjD262XbzbziFqBADxdI/kEQIaMUpyMG2T7CgUlJTF2CkUi0FgvQTm2FB+"
    "jsFjGVkQKUSQCQASZy8PQxBGpt4+fbnVXiJ9NUXcfFEQ48qSrw1wARAF+D2AGazDwdzzPxH+"
    "V/F0RhLLpBn+WDIfUwE5AIRliEoj4k+uge0GmB0dMswKV4OFcd3nWwOUCMTmMPo6AuCVtd0B"
    "AOCqfFNQNmSzIQp31Ie+YzLuxbzgVWP3CADQ1JRYBZG804ya4of4jiqO4szcdGg3uEBeCY8+"
    "fMRCiaOwZmFOX4R2PVMk21L34k5gHgljyzY+zZuYzNdQGp9FxCcVbUb6XgCMvBJeTQPahIXv"
    "4w6MlQNYrzutiOJ+LZ7OSHsCzEwuwT2lA4YJVKvIhzqxKiWTbjuQTaSvpLaLEud6ulvUS8MA"
    "QK1dNzjnvAhwveppSOqBFJzyCmCXELSXEbXn4Yalc9qMRNxROXeyVbuqzo4+M1z1red7GTE1"
    "92bgfmPLSVm28x01cqNGAmq+OhSkw1iPnJBtb1QJmD8UMI/m38e6cq8fGwD+vYMjmYcpMNeg"
    "Q65kmfkBlxtupwrB3NA5t/pzQ3f++pdfBQztq+DiLBEAAAAASUVORK5CYII="
    )

catalog["refresh.png"] = "refresh_png"
GetData_refresh_png   = refresh_png.GetData
GetImage_refresh_png  = refresh_png.GetImage
GetBitmap_refresh_png = refresh_png.GetBitmap
GetIcon_refresh_png   = refresh_png.GetIcon

#---------------------------------------------------------------------

resize_fit_png = PyEmbeddedImage( 
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAdZJ"
    "REFUOI2Njr1rE3EYxz93udyZF1pqgi0GpaDgUMgkpQ6Sq4NmKYKodHPSoa6CxMktOHQWKg5u"
    "8WXRP0CTtdZuJR0clA6SloJpLvfWu9/j0DbkIJJ84AcPv+/3+fBoj+uHAqBBa6NWsBnDk/ph"
    "U6AC8KZW0PQg8AkDf6JlgI1awQ4DvxUEPgCG53mtj6+u2vee7TZ1Xa+MEyilWu9eluwHz382"
    "E0F1bVsmobq2LcN7xtngOA5KBCWJPIGuaTiOk/gbCFy3TyTC0/o3pnLWoCAISqDXD3j94hau"
    "2x8t8DyfSCkuzp1nOm+ilKCUEMWC0/PY3zsgUgrP85NXnQ1hGBGJEPR0jrrg9hXTJhz99fj9"
    "q8txbBGJEIbR6AtENCKliGKTvitcmstxpagTxgb7nWNK8zNESiGijRboukmkFDOzU6StFCoF"
    "7Y7PXkcxf+0y5zInua6bowXpdJZYhIe300Nx9vSdEIuQTmcZZiAwzTwpwyCTTRaGSRkGpplP"
    "ChZXd5qbjYX7Qbe9tfIof/2/26cE3fYWcGFxdefDZmPBNiwrVylXG1/+/Fhf2T34ro8TFIs3"
    "pXzn/WfLyi0BGIaRoVBavlEsLTe+vp21xwnKdz81BZbG9SbmH1h98DCb/GHYAAAAAElFTkSu"
    "QmCC"
    )

catalog["resize-fit.png"] = "resize_fit_png"
GetData_resize_fit_png   = resize_fit_png.GetData
GetImage_resize_fit_png  = resize_fit_png.GetImage
GetBitmap_resize_fit_png = resize_fit_png.GetBitmap
GetIcon_resize_fit_png   = resize_fit_png.GetIcon

#---------------------------------------------------------------------

home_png = PyEmbeddedImage( 
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAhlJ"
    "REFUOI2Fk89L1EEYxj8zO+3ahm1mKyplBYWH6CAd6uTRU5egQ4QZ4nXBi50lIoIUCvLaP9Al"
    "iDrYHxCdunjsUhFY/lhdddfvd+Z9ZzqYrrKUL8zhfed5PswwzxiAx+/8zFp9u6ZKBUPkf5Ww"
    "BUvj3JlTC7N3uubN7Fs/8/VnY85ZA+aoVmMCoGBNB0c0cXmw+5FbXt2sWZMAA6ktyEJk6KwD"
    "4Edd6DphjwCsSayub9WcaKwkhWja7lYeGexxzD3oBaD2epXlDaFcakNSApFUsUFiVBVUFVWl"
    "0fQMVQu8mqoeiBemqlzoNWw1/YFOVQgao1WJB8PNbc+1844XD/s67vxysp/hQcfmziGIRGwI"
    "ARFhrZFx82oXz8YH/vkAzycGuHGpxPpWhogQQsAGUZqtwP3RHmbv9f/TvF9Pxge4e6tCazcQ"
    "RLESlIKJfPi8xsj00rGAkeklFr/UsUQkKC7kHgzsCCDhWECSQLNlsAaiKC7PA9buhU+C7zAM"
    "T35ioymsvBnd0/gcDQkFYrS4PPc4CyQIWecJTpcAafc+C4TMggGJ4HyW2+giCcjyvAOgISP3"
    "bbDPd8lDxAAi1prrE4vfis5e3M/x73pOOhTpvp4S1sLKhifGRH9v6e+OwUv8XihemXJll42J"
    "QNTEyaKlXGqvFNORedS9niTUm8WnBqB6++NMt2vVTMFUiMd8Z4tNmhotKS/8ej82/wdzWy56"
    "dzw68gAAAABJRU5ErkJggg=="
    )

catalog["home.png"] = "home_png"
GetData_home_png   = home_png.GetData
GetImage_home_png  = home_png.GetImage
GetBitmap_home_png = home_png.GetBitmap
GetIcon_home_png   = home_png.GetIcon

#---------------------------------------------------------------------

info_png = PyEmbeddedImage( 
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAtxJ"
    "REFUOI1tkztsHFUUhr+587gzsw+Pdw3BdmR7o41JkShEoqRzRE9LEYk6mAJZkZCwLBASUhRF"
    "AkMBTaRI0NMkTVJFKRCisg04heMEcMxmvWt2d/beee2lWLQ4Eaf6i/P9Okf/ORYv1+Laa1QW"
    "37OEWAkC/wxYKKX2zGh0n/6TWzy5cXiy3XpBX9i8FkXRxtL8QlCVZRzbwfMlsiQ5jnvs7P6q"
    "2q3nn7C1eh0wAPYEPv/VreXm2bW58qtu1tWYrGB2WlGWOToNqJYizp173ZWhvHyQXVqideeH"
    "/wwufHltuXl2LUgcsmFGUApZOm34fvMt3nl7ngc/H5JZVczIolZ/BTd03zgsLg5p3X0oaHxw"
    "KopqG9NOBZMbwkqJsFLCD/3JfrbrYglBbgyDWDM3v0StPrNB46NTDmHzSuP0QpgeJ4SVMkEp"
    "xA8DennE1U9/Qjg23bxBjkGnKbFOiLVmsdkMO0edK44lxMp0eQqVqjFcCpCBJJQxn394kWJk"
    "eP/mnwyzErFOGAwVsVJUoxJgrTi+9BueI7EqAj8M8AKJKz1mZxJqUQBAJUh51hMMhpqBUiid"
    "4Po2UsqGgzBGhhJHuHiBxPE8hGNjTgQ81Am9eESsNEonZHn+b3bGCDVM9hzfQ4Y+rhzDBZAV"
    "oxcM+rFiqPQEdmxBopI9AcW99nEb1/ewbJsCg84ykiybGKgkQSWavCgAEMIiVX3A3BMc7dze"
    "+mWn7wQuuTGoNCPWmqFOJgZZllGcmKher/L7/n6f9PFtwbNv253W0frWb9vk1oiB0vTiId2e"
    "mgCxzie6UglRvTb9TnedRzfb40t8fvfHv0aXZm1PvFmeiugeD3jaijk4OOTOw6c82MmxHYeZ"
    "mSmyuMveo91v2F5df/mZ4PwXq9Va/bOFRqPq+mXywowvUUCi+vyx/7jX7/79Mdurm//3jeOa"
    "u1qntvwu2Jc9zz0DkKbZHozu09n9joOvj062/wMDokUH4SBw6gAAAABJRU5ErkJggg=="
    )

catalog["info.png"] = "info_png"
GetData_info_png   = info_png.GetData
GetImage_info_png  = info_png.GetImage
GetBitmap_info_png = info_png.GetBitmap
GetIcon_info_png   = info_png.GetIcon

#---------------------------------------------------------------------

filelog_png = PyEmbeddedImage( 
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAidJ"
    "REFUOI2Nk0tIlFEUx3/3e87nahYVRrSIMWvRoiJaBVYUhItABMkHhYSEuTAzUkuxl+HQ2IMe"
    "s7AgEweCIKpFBLVwKW2jB2EtolWL2oj1fffe02Ia6RsTOpt7OZz7P//z41wF0DmQ/25EsiLC"
    "yuF8m74ysKY66wFYkWzTgX2ICAoFChAQEaxYRODzl6+r2/rGSqVrZ9uWCYgIidY8efEK13Gg"
    "/B5tDAf37+Xhs+c8vn2Bi8Wktf3kZTVz9Uzrkq/KRYwl9BwiFyIPAlfhKgetDY5SSLLISHcL"
    "WzbXHTp8evxRlYBCG4vnuHzYM8j73YMgMF0Y4mccs35tLc0nxmnqGWVdbS0IzakRUGCshSBD"
    "/VwRAONnaD81zqpslo25DWyqy+F7LsaY5RABtLbghxSfHkMEuhrvMFPoTRV3DhXYtWN7GXK1"
    "gLGGAKG36S6IECYxRwYmiBMNCIHnEWUCxNrlDhRgEo2vLK+3HQWBrXM3mcr3p4qPn7tFYuzf"
    "BioMFMZaHC9k55spRMoMuoZvkCQaAN/ziKIQawwoVSUAJFbAj8iX2hCB/pYHTF7qSjnoG5tE"
    "2/S2LglYrQkwjHSUEITgV0zP+WLKQU0UYrRegYExhI7lZX0HItDw9h6F0e5U8dDEfYwx/2Yg"
    "Ar4f0vipBAg6U8Pw9ZnyfgCu45AJo3K7agbx4sLsu/mPDeXPJFSmrBoXpRRKKeLFhdml3J8z"
    "B2T5//gBzAP8BrKg5xzZN1ctAAAAAElFTkSuQmCC"
    )

catalog["filelog.png"] = "filelog_png"
GetData_filelog_png   = filelog_png.GetData
GetImage_filelog_png  = filelog_png.GetImage
GetBitmap_filelog_png = filelog_png.GetBitmap
GetIcon_filelog_png   = filelog_png.GetIcon

#---------------------------------------------------------------------

resize_actual_png = PyEmbeddedImage( 
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAhJJ"
    "REFUOI2lk0FLG1EQx3+7ZheSiuJSpW5YPHhQU1oM7UkoNLXmoFJLwFK8FLz0Cwh+Bj9CL95L"
    "D+kH0OpRqKW20koPgSLowQhLMO6+ffuyrwfZJYHk1IGBmf+838C8N8+gj23uNN2hxLxI846Z"
    "FHe3xy/7nTX7ibvb45eBCCpRJAhEUBkEAxhpsL599kjroZ/dxYfTBX41gl7A6Dz+tDN3mua5"
    "NGi1bqsvpq94Xz5Fa029Xocf4GlNrVbDMAw+fH/El8ZEFcgaZCMEQbAwO3pOGIYIIXAcB8dx"
    "GBkZQQhBGIbMjp4TBMFCzx2UX3127xrc1tYWHSZLJSZLJTzPw/M8XNfNtLVFhyC4rQGkXE50"
    "9MXMSr0ShgLZbiPDEADf9/F9n3w+T7vZBMDO5wlDi5mV+nPR0QeAYUqpUFIdlOfGUEqh4hgV"
    "x/i+z9LqKjc3N5mmlKI8N4aS6kBKdTeC1gYkVI5OrlFRhJISJSWVahUlJUvLy5mmooijk2tI"
    "qGh994CmRa7Y2F8/NE0bKQSxlANdCoFp2jT21w8tckWA3J+915cAllUgFgIVx4N2BrTGsgoA"
    "pFy2B7Y9jIwidJIM5JMkwbaHe7S0wf2odXb85uPbp93FJ6Vhvv1u9wBR6+sxMAFcdesF4AHg"
    "pj41v7Xx7N1fPTW/tdGtA5PAvRQ06GMvN5tux0iy3zikzeLe7uAP9V/2D3BVC8av8wz4AAAA"
    "AElFTkSuQmCC"
    )

catalog["resize-actual.png"] = "resize_actual_png"
GetData_resize_actual_png   = resize_actual_png.GetData
GetImage_resize_actual_png  = resize_actual_png.GetImage
GetBitmap_resize_actual_png = resize_actual_png.GetBitmap
GetIcon_resize_actual_png   = resize_actual_png.GetIcon

#---------------------------------------------------------------------

wafermap_png = PyEmbeddedImage( 
    "iVBORw0KGgoAAAANSUhEUgAAAHEAAABxCAYAAADifkzQAAAABHNCSVQICAgIfAhkiAAABAhJ"
    "REFUeJztnUFO20AYhZ8dtysQlVCqoKbCLLLorr1Byx16Bg7AjkWW7HoAztA7tEeguy5YYNpI"
    "WI0iUZVVCUkXlYAEmPntjB3n8b5l/DMz4YtsvRl7HEVxC2K1SZY9gIdoxdG0rr66r2x1Zz+n"
    "UbUjKU8jJQLA+GTsLtgBcOppxFLzHjj97mnmTWP/TQAaLBEAkC543Fqz4sTLHoBYHEkkQBIJ"
    "kEQCJJEASSQgCjljEyqkdzodDAaDhdt58cxf024DV566dnsLx9+GzpqucUxnk/CTBsFzoimk"
    "Hx46SwYHB4Dv5xDBX/Mc2O+5f6SfTq5x8dfdTBadmyYWvCVJNbG8mlZTz/HNzUq6rZR02QN4"
    "HF0TCZBEAiSRAEkkQBIJkEQCzGHfEuRDhfRQWMI+AFxcLd5Xaqhpb23heOieNACA64ITAoUk"
    "moJ8iJC+qjVHR+6avT3vjEDSSwpLLB7208J/Ie6SOo5l5ZrUNZEASSRAEgmQRAIkkQBJJMCc"
    "E7dfR1PAkxMBZGfu4y+jjqm/X9PcVMdGklScE/23u8MfimPgqPXZWbJ3/dEWnC01TQv7rnYy"
    "AD1PPw+g0ykBkkiAJBIgiQRIIgGSSIAkEhBFccu0av/ubRvD4bm3wSaF/Xht11Q3ufyycF+h"
    "6Ha7yHP/d787IXAjkXHVPl7fRbT2wVkzvfyKyR+PxAiY/HaftOKNSbjvVXD1f3bGJvV0IOoh"
    "dRzL7n+kayIBkkiAJBIgiQRIIgGSSMBtxNgxVFvWm5tUs/Y/B4boK96YBGknSM3cUv5s2E89"
    "DTcoyD/Zmux+2NfplABJJEASCZBEAiSRAEkkQBIJuM2JY/eicJ2r5Om2rc53F0Gd1Lk/wPyt"
    "/rfZ/xTusL8O0yp5kMCbBnpkoM6QbtwMcOHHAUYjoN+f+UinUwIkkQBJJEASCZBEAiSRAEkk"
    "QGE/EMsM+zcST8Zj78J+456RZ63xhP2k39fKPhuSSIAkEiCJBEgiAZJIwMy9xNmSBiHmGI0K"
    "lZuf2W/aTvt1Uuc+A2We2U/mP3iMPM+n3tV/6yZ1q7b5nnVTwQBBPp8L8hZ0TSRAEgmQRAIk"
    "kQBJJEASCZBEAoq9tc2z+s9KnWG/zG78hSRq9b/imqzcq/d0OiVAEgmQRAIkkQBJJEASCSj8"
    "YuisgkE8KbLwTRbKib6ap7z6b6HMqr0Fs0QL1gmBWne2DzX5EOC1emWCvAVdEwmQRAIkkQBJ"
    "JEASCZBEAgqHfQuZ7/iPKnqtGMut9Vnlo3iQ4DkxRDtNmzSwhnQLVeTEoBJDYb6LINCEgCej"
    "o1filok60TWRAEkkQBIJkEQCJJEASSSgkrAfimzhAluNpZkm09icuOwxzNPknNhIiaIYuiYS"
    "IIkE/AMpMHNU5/chEAAAAABJRU5ErkJggg=="
    )

catalog["wafermap.png"] = "wafermap_png"
GetData_wafermap_png   = wafermap_png.GetData
GetImage_wafermap_png  = wafermap_png.GetImage
GetBitmap_wafermap_png = wafermap_png.GetBitmap
GetIcon_wafermap_png   = wafermap_png.GetIcon

#---------------------------------------------------------------------

directory_png = PyEmbeddedImage( 
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAANdJ"
    "REFUOI3V0jFKA1EQxvH/vH1BU8hewkulSxts34J6gQjb2Wxn4S1yhSCewNJSdFdxJ2t8byyU"
    "ECwCj60y3TDMj29g4OhLAKqqWprZQkTK/aGZdSLS1HV9dVAJIbSqav9LVS2E0B5MML++Wwrp"
    "0nBZ0Z1tmcZ24w0WN2HG9GSSBby9f3J7vzr1AuXzS09KlgX4wvHa9XgA3XxnLQMMxF8IQId8"
    "YJcEoB+24wAdD4w4waDr9assiiJrMcaIQecFmvXD44UTOcsBktmHE2nkrz+HzFeEBDz9AJW+"
    "Zovz1/WAAAAAAElFTkSuQmCC"
    )

catalog["directory.png"] = "directory_png"
GetData_directory_png   = directory_png.GetData
GetImage_directory_png  = directory_png.GetImage
GetBitmap_directory_png = directory_png.GetBitmap
GetIcon_directory_png   = directory_png.GetIcon

